import { state } from '../../app/state.js'
import { sanitizeRiskSettings } from '../../domain/risk-plan.js'
import { privateCurrency, escapeHtml } from '../../shared/formatters.js'
import { planningChart } from '../../shared/planning-chart.js'
import { renderHorizonForm } from './horizon.js'

export function renderAnnualRisk(view, stale) {
  const settings = sanitizeRiskSettings(state.plan.riskSettings)
  const money = value => privateCurrency(value, state.valuesHidden, true, state.currency)
  const number = (name, label, value, min, max, step = 1) => `<label class="form-field"><span>${label}</span><input name="${name}" type="number" value="${value}" min="${min}" max="${max}" step="${step}" required /></label>`
  const heading = `<section class="page-heading"><div><p class="eyebrow">FINAPP ANUAL · REVISÃO 2</p><h1>Risco de consumir o patrimônio até a idade-alvo</h1><p>Mesmo fluxo de caixa e patrimônio inicial da avaliação anual. Retornos reais anuais normais, com piso de −99,9999%, e rendimento parcial apenas no primeiro ano.</p></div><a href="/viabilidade" data-route>Conferir premissas e liberações</a></section>`
  const form = `<section class="panel settings-card"><h2>Premissas do risco anual</h2><p>FCX = receitas menos custos e metas. No modo finapp, previdência externa aumenta ativos financeiros e fica fora do FCX. Liberações não criam receita. Saldo de fluxo negativo indica consumo de patrimônio, não necessariamente patrimônio esgotado.</p>${renderHorizonForm()}${state.valuesHidden ? '<p>Mostre os valores para alterar premissas e calcular.</p>' : `<form data-risk-form><input type="hidden" name="method" value="annual" /><input type="hidden" name="horizonMode" value="target" /><input type="hidden" name="months" value="120" /><input type="hidden" name="targetAssets" value="0" /><div class="form-grid form-grid--two">${number('annualVolatility', 'Desvio-padrão do retorno real anual (%)', settings.annualVolatility * 100, 0, 100, 0.1)}${number('simulations', 'Quantidade de percursos', settings.simulations, 50, 1000)}${number('seed', 'Semente reproduzível neste aplicativo', settings.seed, 0, 4294967295)}</div><div class="wizard-actions"><button class="button button--primary" ${view.running ? 'disabled' : ''}>${view.running ? 'Calculando…' : 'Calcular risco anual e matriz'}</button><button type="button" class="button button--secondary" data-risk-cancel>Cancelar cálculo</button></div></form>`}<p role="status">${view.running ? 'Calculando percursos anuais em segundo plano.' : stale ? 'O plano mudou. Execute novamente.' : escapeHtml(view.error)}</p><p>Taxa e fração inicial vêm de <a href="/viabilidade" data-route>Premissas anuais</a>. Probabilidade finapp significa AF não negativo em todos os fechamentos até a idade-alvo. Não equivale a liquidez disponível. A matriz mostra também falta de liquidez.</p><details><summary>Limites e comparação com o finapp</summary><p>Mesma distribuição anual e recorrência financeira. O gerador aleatório é diferente do Python: a mesma semente não produz os mesmos sorteios entre os dois sistemas. Compare resultados exatos com os mesmos percursos ou volatilidade zero. Estes gráficos são reais, sem sorteio de inflação ou câmbio. Consórcios seguem os eventos contratuais cadastrados, sem sorteio uniforme de contemplação da origem. Impostos e custos de venda não cadastrados não entram. Faixas P10 a P90 não são perdas máximas nem garantia.</p><a href="/riscos-mensais" data-route>Simulador mensal legado, metodologia diferente</a></details></section>`
  const result = view.result?.method === 'finapp-annual' && !stale ? view.result : null
  if (!result) return heading + form
  const { base, simulated, matrix } = result
  const rows = base.rows.map((row, index) => ({ ...row, ...simulated.series[index] }))
  const common = { rows, currency: state.currency, hidden: state.valuesHidden, markers: base.retirement ? [{ year: base.retirement.slice(0, 4), label: 'Aposentadoria' }] : [] }
  const charts = planningChart({ ...common, title: 'Ativos financeiros: cenário base e Monte Carlo anual', series: [{ key: 'financialAssets', label: 'AF base', color: '#334155', dash: '4 3' }, { key: 'afP50', label: 'AF mediana P50', color: '#047857' }], bands: [{ low: 'afP10', high: 'afP90', label: 'AF P10 a P90', color: '#bae6fd' }, { low: 'afP25', high: 'afP75', label: 'AF P25 a P75', color: '#6ee7b7' }] })
  const summary = `<section class="panel settings-card"><h2>Resultado anual pela metodologia finapp</h2><p>${(simulated.probabilitySuccess * 100).toFixed(1)}% dos ${simulated.simulations} percursos mantêm ativos financeiros não negativos até ${rows.at(-1).year}. Média dos 10% piores saldos finais: ${money(simulated.cvar10)}.</p><p>AF inicial: ${money(base.openingFinancial)}. AF final base: ${money(rows.at(-1).financialAssets)}. Liquidez final base: ${money(rows.at(-1).liquidAssets)}.</p><p>${base.firstFailure ? `Primeiro fechamento insuficiente de financeiro líquido ou liquidez: ${base.firstFailure.year}.` : 'Sem insuficiência nos fechamentos anuais do cenário base.'}</p>${base.issues.length ? `<p>Avaliação incompleta. As probabilidades são condicionais e não resolvem estas pendências:</p><ul>${base.issues.map(issue => `<li>${escapeHtml(issue)}</li>`).join('')}</ul>` : ''}${charts}<details><summary>Tabela anual do fluxo e risco</summary><div class="table-scroll" tabindex="0" role="region" aria-label="Auditoria anual do risco"><table><thead><tr>${['Ano', 'Receitas', 'Custos', 'Metas', 'FCX', 'Previdência fora do FCX', 'AF base', 'Liquidez base', 'AF P10', 'AF P50', 'AF P90'].map(label => `<th scope="col">${label}</th>`).join('')}</tr></thead><tbody>${rows.map(row => `<tr><th scope="row">${row.year}</th>${['income', 'costs', 'goals', 'freeCashFlow', 'pensionCredits', 'financialAssets', 'liquidAssets', 'afP10', 'afP50', 'afP90'].map(key => `<td>${money(row[key])}</td>`).join('')}</tr>`).join('')}</tbody></table></div></details></section>`
  const grid = `<section class="panel settings-card"><h2>Matriz anual: custos × retorno real</h2><p>Como no finapp, altera custos, sem multiplicar metas ou contribuições externas. Cada célula mostra AF final e liquidez final. O destaque indica algum fechamento negativo, mesmo se houver recuperação depois.</p><div class="table-scroll" tabindex="0" role="region" aria-label="Sensibilidade anual"><table><thead><tr><th scope="col">Custos</th>${matrix.filter(cell => cell.costMultiplier === result.costLevels[0]).map(cell => `<th scope="col">${(cell.annualRealReturn * 100).toFixed(1)}%</th>`).join('')}</tr></thead><tbody>${result.costLevels.map(multiplier => `<tr><th scope="row">${Math.round(multiplier * 100)}%</th>${matrix.filter(cell => cell.costMultiplier === multiplier).map(cell => `<td class="${cell.minFinancial < 0 || cell.minLiquid < 0 ? 'risk-cell-warning' : ''}">AF: ${money(cell.financialAssets)}<br/>Liquidez: ${money(cell.liquidAssets)}<br/>${cell.minFinancial < 0 ? 'AF negativo no caminho' : 'AF não negativo'}<br/>${cell.minLiquid < 0 ? 'Falta de liquidez no caminho' : 'Liquidez não negativa'}</td>`).join('')}</tr>`).join('')}</tbody></table></div></section>`
  return heading + form + summary + grid
}
