import { state, updatePlan } from '../../app/state.js'
import { finappViability, sanitizeFinappMethod } from '../../domain/finapp-viability.js'
import { escapeHtml, privateCurrency } from '../../shared/formatters.js'
import { planningChart } from '../../shared/planning-chart.js'

export function saveViability(data) {
  const openingYearPeriod = Number(data.get('openingYearPeriod'))
  const chfBrlRate = data.get('chfBrlRate') ? Number(data.get('chfBrlRate')) : null
  if (chfBrlRate !== null && (!Number.isFinite(chfBrlRate) || chfBrlRate <= 0 || chfBrlRate >= 1000000)) throw new Error('Cotação CHF/BRL inválida.')
  if (!Number.isFinite(openingYearPeriod) || openingYearPeriod <= 0 || openingYearPeriod > 1 || !['external', 'cash-funded'].includes(data.get('pensionMode'))) throw new Error('Revise fração do ano e origem das contribuições.')
  const releases = state.plan.investments.filter(row => row.liquidity !== 'available').flatMap(row => {
    const value = data.get(`release:${row.id}`)
    if (!value) return []
    const year = Number(value)
    if (!Number.isInteger(year) || year < new Date().getFullYear() || year > 2199) throw new Error('Ano de liberação inválido.')
    return [{ investmentId: row.id, year }]
  })
  updatePlan({ finappMethod: { chfBrlRate, openingYearPeriod, pensionMode: data.get('pensionMode'), openingConfirmed: data.get('openingConfirmed') === 'on', pensionConfirmed: data.get('pensionConfirmed') === 'on', releases } })
}

export function renderViability({ postRetirementOnly = false } = {}) {
  const settings = sanitizeFinappMethod(state.plan.finappMethod)
  const money = value => privateCurrency(value, state.valuesHidden, true, state.currency)
  let result, error
  try { result = finappViability(state, settings) } catch (failure) { error = failure.message }
  const title = `<section class="page-heading"><div><h1>${postRetirementOnly ? 'Vida financeira após a aposentadoria' : 'O orçamento sustenta a aposentadoria?'}</h1><p>Avaliação anual pela recorrência do finapp, até a idade-alvo. Despesas vêm do orçamento, dívidas, consórcios e metas cadastrados, não da renda desejada. O cálculo começa antes da aposentadoria e preserva o patrimônio consumido ou acumulado.</p></div><a href="/plano" data-route>Revisar idades e aposentadoria</a></section>`
  const form = `<section class="panel settings-card"><h2>Premissas da metodologia anual</h2><p>Taxa real global do plano: ${state.valuesHidden ? 'oculta' : `${(state.plan.annualRealReturn * 100).toFixed(2)}%`}. Esta comparação usa a taxa global do finapp. O simulador mensal continua usando os rendimentos individuais. Fluxos são do ano completo e entram no fim do ano. A fração inicial reduz apenas o rendimento, exatamente como no finapp.</p>${state.valuesHidden ? '<p>Mostre os valores para revisar as premissas.</p>' : `<form data-viability><label class="form-field"><span>CHF/BRL fixo para comparação com finapp, opcional</span><input name="chfBrlRate" type="number" min="0.000001" max="999999" step="any" value="${settings.chfBrlRate ?? ''}" /></label><p>Em branco usa a cotação do aplicativo. Este câmbio vale para fluxo, viabilidade e risco anuais, sem alterar valores de patrimônio já convertidos na importação. Para comparar com a origem, confira também taxa, fração inicial, volatilidade e saldos.</p><div class="form-grid form-grid--two"><label class="form-field"><span>Fração do primeiro ano para rendimento</span><input name="openingYearPeriod" type="number" min="0.01" max="1" step="0.01" value="${settings.openingYearPeriod}" required /></label><label class="form-field"><span>Origem da previdência</span><select name="pensionMode"><option value="external" ${settings.pensionMode === 'external' ? 'selected' : ''}>Crédito externo ao caixa, metodologia finapp</option><option value="cash-funded" ${settings.pensionMode === 'cash-funded' ? 'selected' : ''}>Transferência paga com o orçamento</option></select></label></div><p>Contribuições futuras são liberadas no ano final cadastrado, hipótese usada pelo finapp, não garantia contratual. Os saldos iniciais restritos exigem o ano de liberação abaixo, sem duplicar patrimônio nem gerar receita.</p>${state.plan.investments.filter(row => row.liquidity !== 'available').map(row => `<label class="form-field"><span>${escapeHtml(row.name)}: ano de liberação integral, opcional</span><input type="number" name="release:${row.id}" min="${new Date().getFullYear()}" max="2199" step="1" value="${settings.releases.find(item => item.investmentId === row.id)?.year || ''}" /></label>`).join('')}<label><input type="checkbox" name="openingConfirmed" ${settings.openingConfirmed ? 'checked' : ''} /> Conferi os saldos de abertura do ano-base e suas taxas.</label><label><input type="checkbox" name="pensionConfirmed" ${settings.pensionConfirmed ? 'checked' : ''} /> Conferi a origem das contribuições e as hipóteses de liberação, sem duplicar descontos nas receitas ou despesas.</label><button class="button button--primary">Salvar e recalcular avaliação</button></form>`}</section>`
  if (!result) return title + form + `<section class="panel settings-card"><p role="status">${escapeHtml(error)}</p><a href="/plano" data-route>Configurar horizonte</a></section>`
  if (postRetirementOnly && (!result.retirement || !result.rows.some(row => row.year >= result.retirement.slice(0, 4)))) return title + form + '<section class="panel settings-card"><p role="status">Confirme o mês da aposentadoria e uma idade-alvo que inclua esse período.</p><a href="/fluxo-caixa" data-route>Confirmar mês no orçamento</a></section>'
  const displayRows = postRetirementOnly ? result.rows.filter(row => row.year >= result.retirement.slice(0, 4)) : result.rows
  const last = result.rows.at(-1)
  const status = result.issues.length ? 'Avaliação incompleta: revise as pendências' : result.viable ? 'Cobertura anual suficiente nas premissas informadas' : 'Cobertura insuficiente nas premissas informadas'
  const summary = `<section class="panel settings-card"><h2>${status}</h2><p>Horizonte: ${result.rows[0].year} a ${last.year}. ${result.firstFailure ? `Primeiro fechamento com insuficiência financeira ou de liquidez: ${result.firstFailure.year}.` : 'Sem déficit nos fechamentos anuais calculados.'} ${result.firstRetirementFailure ? `Insuficiência na fase de aposentadoria: ${result.firstRetirementFailure.year}.` : ''}</p><dl><dt>Financeiro líquido de dívidas na data-alvo</dt><dd>${money(last.netFinancial)}</dd><dt>Liquidez na data-alvo</dt><dd>${money(last.liquidAssets)}</dd><dt>Patrimônio total na data-alvo, incluindo bens</dt><dd>${money(last.netWorth)}</dd></dl><ul>${result.issues.map(issue => `<li>${escapeHtml(issue)}</li>`).join('')}</ul><p>Um imóvel ou saldo bloqueado não paga automaticamente o orçamento. Resultado anual positivo não prova liquidez dentro de cada ano. <a href="/riscos-mensais" data-route>Confira também déficits mensais</a>. Esta projeção é condicional às premissas, não uma certificação ou garantia.</p></section>`
  const common = { rows: displayRows.map(row => ({ ...row, outflows: row.costs + row.goals })), currency: state.currency, hidden: state.valuesHidden, markers: result.retirement ? [{ year: result.retirement.slice(0, 4), label: 'Aposentadoria' }] : [] }
  const charts = planningChart({ ...common, title: 'Fluxo de caixa anual, metodologia finapp', series: [{ key: 'income', label: 'Receitas', type: 'bar', color: '#0ea5e9' }, { key: 'outflows', label: 'Saídas, custos + metas', type: 'bar', color: '#f59e0b' }, { key: 'pensionCredits', label: 'Créditos previdenciários', type: 'bar', color: '#8b5cf6' }, { key: 'releases', label: 'Liberações, não são receita', type: 'bar', color: '#0f766e' }, { key: 'freeCashFlow', label: 'FCX', color: '#047857' }] }) + planningChart({ ...common, title: 'Cobertura financeira e liquidez até a idade-alvo', series: [{ key: 'netWorth', label: 'Patrimônio total líquido', color: '#475569', dash: '5 3' }, { key: 'financialAssets', label: 'Ativos financeiros', color: '#047857' }, { key: 'liquidAssets', label: 'Liquidez, pode ser negativa', color: '#0369a1' }, { key: 'restrictedFinancial', label: 'Parcela restrita', color: '#7c3aed', dash: '2 3' }] })
  const table = `<details class="panel settings-card"><summary>Conferir cálculo ano a ano</summary><div class="table-scroll" role="region" tabindex="0" aria-label="Auditoria anual"><table><thead><tr>${['Ano', 'AF inicial', 'Receitas', 'Custos', 'Metas', 'FCX', 'Previdência', 'Liberações', 'AF final', 'Liquidez final', 'Dívidas', 'Situação'].map(label => `<th scope="col">${label}</th>`).join('')}</tr></thead><tbody>${result.rows.map(row => `<tr><th scope="row">${row.year}</th>${['previousFinancial', 'income', 'costs', 'goals', 'freeCashFlow', 'pensionCredits', 'releases', 'financialAssets', 'liquidAssets', 'liabilities'].map(key => `<td>${money(row[key])}</td>`).join('')}<td>${row.netFinancial < -0.005 || row.liquidAssets < -0.005 ? 'Insuficiência' : 'Sem déficit anual'}</td></tr>`).join('')}</tbody></table></div></details>`
  const phase = postRetirementOnly ? `<section class="panel settings-card"><h2>Orçamento na fase de aposentadoria</h2><p>Aposentadoria cadastrada: ${result.retirement}. O primeiro ano mostrado inclui seus 12 meses, inclusive os anteriores ao mês da aposentadoria, conforme o modelo anual do finapp. Valores abaixo são totais anuais, não apenas o último mês.</p><p>AF na abertura do primeiro ano mostrado: ${money(displayRows[0].previousFinancial)}. Liquidez: ${money(displayRows[0].previousLiquid)}. Esses saldos já refletem receitas, despesas e investimentos dos anos anteriores.</p><div class="table-scroll" tabindex="0" role="region" aria-label="Orçamento anual após aposentadoria"><table><thead><tr><th scope="col">Ano</th><th scope="col">Receitas</th><th scope="col">Custos</th><th scope="col">Metas</th><th scope="col">Despesas no FCX</th><th scope="col">FCX</th><th scope="col">AF final</th><th scope="col">Liquidez final</th></tr></thead><tbody>${displayRows.map(row => `<tr><th scope="row">${row.year}</th>${[row.income, row.costs, row.goals, row.costs + row.goals, row.freeCashFlow, row.financialAssets, row.liquidAssets].map(value => `<td>${money(value)}</td>`).join('')}</tr>`).join('')}</tbody></table></div><a href="/viabilidade" data-route>Ver também os anos anteriores à aposentadoria</a></section>` : ''
  return title + summary + phase + `<section class="panel settings-card">${charts}</section>` + table + form
}
