import { state } from '../../app/state.js'
import { categoriesForType } from '../../data/cash-flow-categories.js'
import { currencies } from '../../shared/currencies.js'
import { escapeHtml, privateCurrency } from '../../shared/formatters.js'

export function renderBudgetStep() {
  const frequencyLabels = { monthly: 'Mensal', annual: 'Anual', occasional: 'Único' }
  return `<section class="panel settings-card budget-step"><h2>Receitas e despesas, no seu ritmo</h2><p>Informe o valor na moeda original. O orçamento converte para ${state.currency}. Valores anuais entram como provisão de 1/12, não como pagamento mensal.</p>
    <form data-guided-budget><fieldset><legend>1. O que e quanto</legend><div class="form-grid form-grid--two"><label class="form-field"><span>Categoria</span><select name="categoryId">${['income', 'expense'].map(type => `<optgroup label="${type === 'income' ? 'Receitas' : 'Despesas'}">${categoriesForType(type, state.customCategories).map(category => `<option value="${escapeHtml(category.id)}">${escapeHtml(category.name)}</option>`).join('')}</optgroup>`).join('')}</select></label><label class="form-field"><span>Descrição</span><input name="description" maxlength="60" required /></label><label class="form-field"><span>Valor por ocorrência</span><input name="amount" type="number" min="0.01" max="1000000000" step="any" required /></label><label class="form-field"><span>Moeda do lançamento</span><select name="currency">${Object.keys(currencies).map(code => `<option ${code === state.currency ? 'selected' : ''}>${code}</option>`).join('')}</select></label></div></fieldset>
    <fieldset><legend>2. Quando acontece</legend><div class="form-grid form-grid--two"><label class="form-field"><span>Frequência</span><select name="frequency"><option value="monthly">Mensal</option><option value="annual">Anual</option><option value="occasional">Único</option></select></label><label class="form-field"><span>Início opcional, obrigatório para único</span><input name="startDate" type="date" /></label><label class="form-field"><span>Término</span><select name="endMode"><option value="none">Sem término</option><option value="date">Data manual</option><option value="retirement">Receita até a aposentadoria</option></select></label><label class="form-field"><span>Fim, somente para data manual</span><input name="endDate" type="date" /></label></div><p>Início e fim incluem o mês inteiro. O vínculo com a aposentadoria vale apenas para receitas recorrentes.</p></fieldset><div class="wizard-actions"><button class="button button--primary" type="submit">Adicionar lançamento</button></div></form>
    <h3>Lançamentos cadastrados</h3><div class="budget-entry-list">${state.cashFlow.items.map(item => `<article><strong>${escapeHtml(item.description || item.categoryId)}</strong><span>${item.type === 'income' ? 'Receita' : 'Despesa'} · ${privateCurrency(item.amount, state.valuesHidden, false, item.currency)} · ${frequencyLabels[item.frequency]}</span><small>${item.startDate || 'Sem início definido'} → ${item.endMode === 'retirement' ? 'Aposentadoria' : item.endDate || 'Sem término'}</small></article>`).join('') || '<p>Nenhum lançamento. Comece por uma receita e pelas despesas que já conhece.</p>'}</div>
    <p><a href="/fluxo-caixa" data-route>Editar lançamentos, importar extrato e ver orçamento completo</a></p><div class="wizard-actions"><a href="/construir/objetivo" data-route>Voltar ao objetivo</a><a class="button button--primary" href="/construir/patrimonio" data-route>Continuar para patrimônio</a></div></section>`
}
