import { state } from '../../app/state.js'
import { renderReconciliation } from './reconciliation.js'
import { accountBalances, sanitizeLedger } from '../../domain/accounts.js'
import { currencies } from '../../shared/currencies.js'
import { escapeHtml, privateCurrency } from '../../shared/formatters.js'
export function renderAccounts() {
  const ledger = sanitizeLedger(state.cashFlow.ledger)
  const today = new Date().toISOString().slice(0, 10)
  const rows = accountBalances(ledger, today)
  const options = ledger.accounts.map(item => `<option value="${item.id}">${escapeHtml(item.name)} (${item.currency})</option>`).join('')
  const field = (name, label, type, extra = '') => `<label class="form-field"><span>${label}</span><input name="${name}" type="${type}" ${extra} required /></label>`
  return `<section class="page-heading"><h1>Contas e movimentos</h1><a href="/fluxo-caixa" data-route>Voltar ao orçamento</a></section><section class="panel settings-card"><p>Saldos realizados em ${today}. Contas não são somadas ao patrimônio da aposentadoria ou à reserva. Movimentos não criam lançamentos no orçamento. Transferências apenas movem saldo entre contas.</p>
    <div class="budget-entry-list">${ledger.accounts.map(item => { const row = rows.find(row => row.id === item.id); return `<article><strong>${escapeHtml(item.name)} (${item.currency})</strong><span>${row ? privateCurrency(row.balance, state.valuesHidden, false, item.currency) : 'Abertura futura'}</span>${state.valuesHidden ? '' : `<button type="button" class="button button--secondary" data-account-edit="${item.id}">Editar conta</button>`}<button type="button" class="button button--secondary" data-account-remove="${item.id}">Excluir conta</button></article>` }).join('') || '<p>Cadastre sua primeira conta com o saldo na data de abertura.</p>'}</div>
    ${state.valuesHidden ? '<p>Mostre os valores para cadastrar contas e movimentos.</p>' : `<details><summary>Cadastrar ou editar conta</summary><form data-account-form><input type="hidden" name="id" value="" /><p data-ledger-edit-label>Novo registro</p><div class="form-grid form-grid--two">${field('name', 'Nome da conta', 'text', 'maxlength="60"')}${field('openingBalance', 'Saldo inicial', 'number', 'step="any" min="-1000000000" max="1000000000"')}${field('openingDate', 'Data do saldo inicial', 'date', `value="${today}"`)}<label class="form-field"><span>Moeda</span><select name="currency">${Object.keys(currencies).map(code => `<option>${code}</option>`).join('')}</select></label></div><div class="wizard-actions"><button class="button button--primary">Salvar conta</button><button type="button" class="button button--secondary" data-ledger-cancel>Cancelar edição / novo registro</button></div></form></details>
    ${ledger.accounts.length ? `<details><summary>Cadastrar ou editar movimento</summary><form data-movement-form><input type="hidden" name="id" value="" /><p data-ledger-edit-label>Novo registro</p><div class="form-grid form-grid--two"><label class="form-field"><span>Tipo</span><select name="type"><option value="income">Entrada</option><option value="expense">Saída</option><option value="transfer">Transferência</option></select></label><label class="form-field"><span>Conta de origem</span><select name="accountId">${options}</select></label>${field('amount', 'Valor na moeda da origem', 'number', 'min="0.01" max="1000000000" step="any"')}${field('date', 'Data', 'date', `value="${today}"`)}<label class="form-field"><span>Destino, somente transferência</span><select name="destinationId">${options}</select></label><label class="form-field"><span>Valor recebido na moeda de destino, somente transferência</span><input name="receivedAmount" type="number" min="0.01" max="1000000000" step="any" /></label></div><p>Em moedas diferentes, informe o valor efetivamente recebido. Registre tarifas como saída separada.</p><div class="wizard-actions"><button class="button button--primary">Salvar movimento</button><button type="button" class="button button--secondary" data-ledger-cancel>Cancelar edição / novo registro</button></div></form></details>` : ''}`}
    <h2>Movimentos</h2><div class="budget-entry-list">${ledger.movements.slice().reverse().map(item => `<article><span>${item.date} · ${item.type === 'transfer' ? 'Transferência' : item.type === 'income' ? 'Entrada' : 'Saída'} · ${escapeHtml(ledger.accounts.find(account => account.id === item.accountId).name)}</span><span>${privateCurrency(item.amount, state.valuesHidden, false, ledger.accounts.find(account => account.id === item.accountId).currency)}</span>${state.valuesHidden ? '' : `<button type="button" class="button button--secondary" data-movement-edit="${item.id}">Editar movimento</button>`}<button class="button button--secondary" type="button" data-movement-remove="${item.id}">Excluir movimento</button></article>`).join('') || '<p>Nenhum movimento.</p>'}</div></section>${renderReconciliation()}`
}
