import { state } from '../../app/state.js'
import { standardCashFlowCategories } from '../../data/cash-flow-categories.js'
import { escapeHtml, privateCurrency } from '../../shared/formatters.js'

export function renderLedgerLinks() {
  if (state.valuesHidden) return ''
  const ledger = state.cashFlow.ledger
  if (!ledger.accounts.length) return ''
  const accounts = ledger.accounts.map(row => `<option value="${row.id}">${escapeHtml(row.name)} (${row.currency})</option>`).join('')
  const movements = ledger.movements.map(row => `<option value="${row.id}">${row.date} · ${escapeHtml(ledger.accounts.find(item => item.id === row.accountId).name)} · ${row.type} · ${privateCurrency(row.amount, false, true, ledger.accounts.find(item => item.id === row.accountId).currency)}</option>`).join('')
  const today = new Date().toISOString().slice(0, 10)
  const existingActuals = state.cashFlow.items.filter(row => row.recordKind === 'actual' && !row.id.startsWith('ledger:'))
  const labels = { confirmed: 'Confirmado', revoked: 'Desfeito', edited: 'Cancelado por edição', deleted: 'Movimento excluído' }
  return `<section class="panel settings-card"><h2>Conciliação por movimento</h2><p>Copie a data, o valor com sinal e uma referência única do extrato. A confirmação fica salva com o movimento. Editar o movimento cancela sua conciliação. Transferências são conferidas separadamente na origem (valor negativo) e no destino (positivo).</p>
  <details><summary>Histórico de conciliação</summary><p>Últimos 100 eventos do plano. Histórico editável no arquivo local, sem valor de auditoria independente.</p><ul>${(ledger.reconciliationHistory || []).slice().reverse().map(row => `<li>${escapeHtml(row.at)} · ${labels[row.operation]} · ${escapeHtml(row.reference)}</li>`).join('') || '<li>Nenhum evento.</li>'}</ul></details>
  ${ledger.movements.length ? `<form data-movement-reconciliation><div class="form-grid form-grid--two"><label class="form-field"><span>Movimento</span><select name="movementId">${movements}</select></label><label class="form-field"><span>Conta no extrato</span><select name="accountId">${accounts}</select></label><label class="form-field"><span>Data no extrato</span><input name="date" type="date" max="${today}" required /></label><label class="form-field"><span>Valor com sinal na moeda da conta</span><input name="amount" type="number" step="0.01" required /></label><label class="form-field"><span>Referência única do extrato, por exemplo arquivo e ID da operação</span><input name="reference" maxlength="100" required /></label></div><div class="wizard-actions"><button class="button button--primary">Conferir e marcar como conciliado</button></div></form>` : '<p>Cadastre movimentos para começar.</p>'}
  <ul>${ledger.movements.flatMap(row => (row.reconciliations || []).map(match => `<li>${row.date} · ${escapeHtml(ledger.accounts.find(item => item.id === match.accountId)?.name || '')} · ${escapeHtml(match.reference)} · conferido em ${escapeHtml(match.at.slice(0, 10))} <button type="button" class="button button--secondary" data-unreconcile="${row.id}" data-reconcile-account="${match.accountId}">Desfazer conciliação</button></li>`)).join('') || '<li>Nenhuma operação conciliada.</li>'}</ul></section>
  <section class="panel settings-card"><h2>Integrar sem duplicar</h2><p>Associe uma entrada ou saída ao realizado do orçamento. O vínculo cria um único realizado que acompanha as edições do movimento. O planejado continua separado. Transferências não entram como receita ou despesa. Antes de vincular, remova qualquer realizado importado ou manual que represente a mesma operação.</p>
  ${ledger.movements.some(row => row.type !== 'transfer') ? `<form data-budget-link><div class="form-grid form-grid--two">
    <label class="form-field"><span>Movimento de entrada ou saída</span><select name="movementId">${ledger.movements.filter(row => row.type !== 'transfer').map(row => `<option value="${row.id}">${row.date} · ${row.type} · ${privateCurrency(row.amount, false, true, ledger.accounts.find(item => item.id === row.accountId).currency)} ${row.budgetCategoryId ? '(vinculado)' : ''}</option>`).join('')}</select></label>
    <label class="form-field"><span>Categoria do realizado</span><select name="categoryId"><option value="">Desvincular do orçamento</option>${[...standardCashFlowCategories, ...state.customCategories].map(row => `<option value="${row.id}">${row.type === 'income' ? 'Receita' : 'Despesa'} · ${escapeHtml(row.name)}</option>`).join('')}</select></label>
    <label class="form-field"><span>Substituir um realizado existente, se for a mesma operação</span><select name="existingItemId"><option value="">Nenhum realizado existente</option>${existingActuals.map(row => `<option value="${row.id}">${row.startDate} · ${escapeHtml(row.description)} · ${privateCurrency(row.amount, false, true, row.currency)}</option>`).join('')}</select></label>
    </div><div class="wizard-actions"><button class="button button--primary">Aplicar vínculo</button></div></form>` : ''}
  <h3>Atualizar um saldo da Carteira</h3><p>Escolha uma conta que representa um investimento já cadastrado. A confirmação substitui o saldo desse investimento pelo saldo da conta na data escolhida, convertido pela cotação de referência do plano, não pela cotação histórica desse dia. Não soma os dois saldos e não altera os aportes. Alterações futuras exigem nova confirmação.</p>
  ${state.plan.investments.length ? `<form data-portfolio-link><div class="form-grid form-grid--two"><label class="form-field"><span>Conta que representa o investimento</span><select name="accountId">${accounts}</select></label><label class="form-field"><span>Investimento a atualizar</span><select name="investmentId">${state.plan.investments.map(row => `<option value="${row.id}">${escapeHtml(row.name)} · ${privateCurrency(row.amount, false, true, state.currency)}</option>`).join('')}</select></label><label class="form-field"><span>Data do saldo</span><input name="date" type="date" max="${today}" value="${today}" required /></label><label><input name="confirm" type="checkbox" required /> Esta conta representa apenas este investimento. Quero substituir seu saldo.</label></div><div class="wizard-actions"><button class="button button--primary">Confirmar atualização da Carteira</button></div></form>` : '<p>Cadastre um investimento na Carteira antes de associar a conta.</p>'}
  <ul>${ledger.accounts.filter(row => row.investmentId).map(row => `<li>${escapeHtml(row.name)} → ${escapeHtml(state.plan.investments.find(item => item.id === row.investmentId)?.name || 'Investimento removido')}, saldo de ${row.investmentSyncDate}. <button type="button" class="button button--secondary" data-unlink-investment="${row.id}">Desvincular sem alterar saldos</button></li>`).join('')}</ul></section>`
}
