import { state, updateCashFlow } from '../../app/state.js'
import { consortiumFromForm, consortiumSchedule } from '../../domain/consortium.js'
import { currencies } from '../../shared/currencies.js'
import { escapeHtml, privateCurrency } from '../../shared/formatters.js'

export const consortiumView = { preview: null }
export function saveConsortium(data) {
  if (data.get('confirmed') !== 'on') throw new Error('Confirme que estes valores e parcelas não estão cadastrados em duplicidade.')
  const item = consortiumFromForm(data)
  const current = state.cashFlow.consortia || []
  if (data.get('id') && !current.some(row => row.id === item.id)) throw new Error('Consórcio não encontrado.')
  if (!data.get('id') && current.length >= 20) throw new Error('Limite de 20 consórcios.')
  updateCashFlow({ consortia: [...current.filter(row => row.id !== item.id), item] })
  consortiumView.preview = null
}
export function guideConsortiumForm(form) {
  if (!form) return
  const stage = form.elements.namedItem('stage').value
  for (const group of form.querySelectorAll('[data-consortium-pending], [data-consortium-use]')) {
    group.hidden = group.hasAttribute('data-consortium-pending') ? stage !== 'pending' : stage === 'asset'
    for (const field of group.querySelectorAll('input,select')) field.disabled = group.hidden
  }
  const preview = form.querySelector('[data-consortium-preview]')
  if (!preview) return
  try {
    const item = consortiumFromForm(new FormData(form))
    const row = consortiumSchedule(item, 1)[0]
    preview.textContent = `Primeiro mês: saída ${privateCurrency(row.cashExpense, false, true, item.currency)}. Posição líquida vinculada ${privateCurrency(row.restrictedEquity, false, true, item.currency)}. Principal futuro ${privateCurrency(row.principal, false, true, item.currency)}. Crédito não é saldo livre.`
  } catch { preview.textContent = 'Preencha os campos para conferir a parcela e o patrimônio antes de salvar.' }
}
export function renderConsortia() {
  const field = (name, label, value = 0, extra = '') => `<label class="form-field"><span>${label}</span><input name="${name}" type="number" step="${name === 'months' ? '1' : '0.01'}" min="${name === 'months' ? '1' : '0'}" max="${name === 'months' ? '600' : '1000000000'}" value="${value}" ${extra} required /></label>`
  const rate = (name, label) => `<label class="form-field"><span>${label}</span><input name="${name}" type="number" min="-99" max="100" step="0.01" value="0" required /></label>`
  const month = (name, label, value = '', required = false) => `<label class="form-field"><span>${label}</span><input name="${name}" type="month" value="${value}" ${required ? 'required' : ''} /></label>`
  const money = (value, currency) => privateCurrency(value, state.valuesHidden, true, currency)
  return `<section class="page-heading"><div><p class="eyebrow">CAIXA E PATRIMÔNIO</p><h1>Consórcios</h1><p>Separe parcelas, crédito vinculado e bem adquirido. Contemplação não é receita nem rendimento garantido.</p></div><a href="/calendario" data-route>Dívidas e calendário</a></section>
    <section class="panel settings-card"><h2>Como cadastrar sem duplicar</h2><ol><li>Use o demonstrativo atual da administradora. Informe o primeiro mês das parcelas restantes.</li><li>Separe principal de administração, reserva e seguro. Não use juros de financiamento para representar taxa de administração.</li><li>Se ainda não foi contemplado, a data futura será somente uma hipótese. Deixe em branco para não assumir contemplação.</li><li>Não inclua carta ou bem novamente na Carteira e não repita parcelas no orçamento.</li></ol><a class="button button--secondary" href="/riscos" data-route>Ver gráfico patrimonial e Monte Carlo</a></section>
    <section class="panel settings-card"><h2>Contrato e hipóteses</h2>${state.valuesHidden ? '<p>Mostre os valores para cadastrar ou editar.</p>' : `<form data-consortium-form><input type="hidden" name="id" value="" />
      <fieldset><legend>1. Situação e saldos atuais</legend><div class="form-grid form-grid--two"><label class="form-field"><span>Nome do consórcio</span><input name="name" maxlength="60" required /></label><label class="form-field"><span>Moeda</span><select name="currency">${Object.keys(currencies).map(code => `<option ${code === state.currency ? 'selected' : ''}>${code}</option>`).join('')}</select></label><label class="form-field"><span>Situação no mês de referência</span><select name="stage"><option value="pending">Ainda não contemplado</option><option value="credit">Contemplado, crédito não utilizado</option><option value="asset">Bem já adquirido</option></select></label>${month('referenceMonth', 'Primeiro mês das parcelas restantes', new Date().toISOString().slice(0, 7), true)}${field('credit', 'Crédito atualizado, líquido de lance anterior se já contemplado')}${field('principal', 'Principal restante do fundo comum')}${field('months', 'Quantidade de parcelas restantes', 120, 'inputmode="numeric"')}</div></fieldset>
      <fieldset><legend>2. Encargos e atualização</legend><div class="form-grid form-grid--two">${field('administration', 'Taxa de administração total ainda a pagar')}${field('reserve', 'Fundo de reserva total ainda a pagar')}${field('insurance', 'Seguro e outros encargos mensais')}${rate('annualAdjustment', 'Reajuste real anual contratual, acima da inflação (%)')}${rate('creditReturn', 'Rendimento real anual do crédito contemplado não usado (%)')}${rate('assetReturn', 'Valorização ou depreciação real anual do bem (%)')}</div><p>O modelo distribui os saldos por parcelas restantes. Aplica reajuste no aniversário do mês de referência ao principal e encargos. Não presume devolução de fundo de reserva. Confira regras específicas do seu contrato.</p></fieldset>
      <fieldset data-consortium-pending><legend>3. Contemplação futura, somente hipótese</legend><div class="form-grid form-grid--two">${month('awardMonth', 'Mês hipotético de contemplação, opcional')}${month('earlyMonth', 'Cenário antecipado, opcional em conjunto com tardio')}${month('lateMonth', 'Cenário tardio, opcional em conjunto com antecipado')}${field('ownBid', 'Lance próprio aceito na hipótese, sai do caixa')}${field('embeddedBid', 'Lance embutido aceito na hipótese, reduz crédito')}</div><p>Sem data, nenhum lance é executado. Na hipótese, o lance amortiza apenas principal e reduz parcelas mantendo o prazo. Uma oferta não aceita não deve ser cadastrada como lance executado. Revise a distribuição contratual de encargos.</p></fieldset>
      <fieldset><legend>4. Uso do crédito ou bem atual</legend><div class="form-grid form-grid--two"><div data-consortium-use>${month('useMonth', 'Mês de uso do crédito, opcional')}<label class="form-field"><span>Destino</span><select name="useType"><option value="asset">Bem que permanece no patrimônio</option><option value="service">Serviço consumido, não vira patrimônio</option></select></label></div>${field('purchaseValue', 'Preço de compra futuro ou valor atual do bem já adquirido')}</div><p>Compra troca crédito por bem. Diferença acima do crédito exige complemento de caixa. Saldo de crédito não utilizado permanece vinculado. Bem já adquirido não gera nova compra nem repete lances.</p></fieldset>
      <p data-consortium-preview role="status">Preencha os campos para conferir antes de salvar.</p><label><input type="checkbox" name="confirmed" required /> Não repeti estas parcelas no orçamento nem este direito/bem no patrimônio da Carteira. Revisei as hipóteses contratuais.</label><div class="wizard-actions"><button class="button button--primary">Salvar consórcio</button><button class="button button--secondary" type="reset">Limpar e cadastrar outro</button></div></form>`}</section>
      <section class="panel settings-card"><h2>Consórcios cadastrados</h2>${(state.cashFlow.consortia || []).map(item => {
        const rows = consortiumSchedule(item, item.months), first = rows[0]
        return `<article class="consortium-card"><h3>${escapeHtml(item.name)}</h3><p>${item.stage === 'pending' ? 'Não contemplado' : item.stage === 'credit' ? 'Crédito vinculado' : 'Bem adquirido'} · referência ${item.referenceMonth} · ${item.months} parcelas restantes</p><dl><dt>Saída no primeiro mês</dt><dd>${money(first.cashExpense, item.currency)}</dd><dt>Posição vinculada líquida após primeira parcela</dt><dd>${money(first.restrictedEquity, item.currency)}</dd><dt>Principal restante após primeira parcela, já deduzido da posição líquida</dt><dd>${money(first.principal, item.currency)}</dd><dt>Contemplação futura</dt><dd>${item.awardMonth || 'Não presumida'}</dd></dl>${state.valuesHidden ? '' : `<button class="button button--secondary" data-consortium-edit="${item.id}">Editar</button>`}<button class="button button--secondary" data-consortium-remove="${item.id}">Excluir</button><details><summary>Parcelas, lances e evolução do direito</summary><div class="table-scroll" tabindex="0" role="region" aria-label="Cronograma do consórcio"><table><thead><tr><th>Mês</th><th>Fundo comum</th><th>Administração</th><th>Reserva</th><th>Seguro</th><th>Lance próprio</th><th>Embutido</th><th>Caixa total</th><th>Posição líquida</th></tr></thead><tbody>${rows.map(row => `<tr><th scope="row">${row.month}</th>${['common', 'administration', 'reserve', 'insurance', 'ownBid', 'embeddedBid', 'cashExpense', 'restrictedEquity'].map(key => `<td>${money(row[key], item.currency)}</td>`).join('')}</tr>`).join('')}</tbody></table></div></details></article>`
      }).join('') || '<p>Nenhum consórcio. Dívidas de financiamento continuam no calendário.</p>'}<p>Direito não contemplado é uma estimativa de principal amortizado, não valor garantido de resgate. Regras gerais: <a href="https://www.bcb.gov.br/meubc/faqs/s/consorcio" target="_blank" rel="noreferrer">Banco Central</a>.</p></section>`
}
